[github-dark]
        [github-dark.default_colors]
        fg = "#e6edf3"
        bg = "#0D1117"

        [github-dark.normal_colors]
        black = "#484f58"
        red = "#ff7b72"
        green = "#3fb950"
        yellow = "#d29922"
        blue = "#58a6ff"
        magenta = "#bc8cff"
        cyan = "#39c5cf"
        white = "#b1bac4"

        [github-dark.bright_colors]
        black = "#6e7681"
        red = "#ffa198"
        green = "#56d364"
        yellow = "#e3b341"
        blue = "#79c0ff"
        magenta = "#d2a8ff"
        cyan = "#56d4dd"
        white = "#cdd9e5"

[github-light]
        [github-light.default_colors]
        fg = "#1F2328"
        bg = "#ffffff"

        [github-light.normal_colors]
        black = "#24292f"
        red = "#cf222e"
        green = "#116329"
        yellow = "#4d2d00"
        blue = "#0550ae"
        magenta = "#8250df"
        cyan = "#1b7c83"
        white = "#6e7781"

        [github-light.bright_colors]
        black = "#57606a"
        red = "#a40e26"
        green = "#1a7f37"
        yellow = "#633c01"
        blue = "#0969da"
        magenta = "#6639ba"
        cyan = "#1b7c83"
        white = "#424a53"
